### PR TITLE
removed deprecation warning for qrand/qsrand by replacing with QRando…

### PR DESCRIPTION
**Pull request by hakuamesan**
Removed deprecation warning for qrand/qsrand by replacing with QRandomGenerator class.

### CODE REVIEW

**Comment by hakuamesan** [comment]
Tried to remove some more compiler warnings for Deprecated functions. 
Replaced delta() with angleDelta()

Please let me know if it is ok.

**Comment by hakuamesan** [comment]
Tried to remove some more compiler warnings for Deprecated functions.
Replaced QString::SkipEmtpyParts() with Qt::SkipEmptyParts()

Please let me know if it is ok.

**Comment by Gnurou** [comment]
This is now merged, thank you! Also inspired me to fix the remaining deprecated warnings.

**Comment by hakuamesan** [comment]
Thank you. As it was my first patch, I wanted to check if it was ok before I started working on the others.  Will try to help a bit more as I understand the code better. :)

**Pull request merged**
