### PR TITLE
Fix macos build

### PR DESCRIPTION
**Pull request by vovkasm**
I try to fix macOS build. Now I can install app bundle for myself and create installer.

Initial motivation for me was retina support, so this change also here, sorry for mixup things.

I myself tested this pull request with following cases:
1. App build, install and run with Qt 5.6 from official packages (`$HOME/Qt`):
```sh
$ cd $PROJECT && mkdir build && cd build
$ export PATH=$PATH:$HOME/Qt/5.6/clang_64
$ cmake -DCMAKE_INSTALL_PREFIX=$PROJECT/build/dest -DEMBED_SQLITE=1 ..
$ make -j 5
$ make install
$ open dest/Tagaini\ Jisho.app
```
2. App build, install and run with Qt 5.8 (from Homebrew):
```sh
$ cd $PROJECT && mkdir build && cd build
$ export PATH=$PATH:/usr/local/opt/qt/bin
$ cmake -DCMAKE_INSTALL_PREFIX=$PROJECT/build/dest -DEMBED_SQLITE=1 ..
$ make -j 5
$ make install
$ open dest/Tagaini\ Jisho.app
```
3. build, create installer, install, run with Qt 5.8 (from Homebrew):
```sh
$ cd $PROJECT && mkdir build && cd build
$ export PATH=$PATH:/usr/local/opt/qt/bin
$ cmake -DCMAKE_INSTALL_PREFIX=$PROJECT/build/dest -DEMBED_SQLITE=1 ..
$ make -j 5
$ cpack -G DragNDrop
$ open Tagaini\ Jisho-1.0.90.dmg # then install and run
```

Main changes (more verbose in commit messages):
1. Properly set arguments to fixup_bundle
2. Install qt plugins (currently only platform plugin, if we need more, I can update)
3. Move some install commands so fixup_bundle run only after app install
4. Modify Info.plist so that macOS know that application supports Retina
5. Remove hardcoded SYSROOT paths, CMake can autodetect it
6. Update README.md (may need some rewording)

Potential gotchas:
1. I tested only with CMake 3.8.1 (older versions can fail, but macOS users will probably have fresh cmake, and I do not touch non-mac things, probably)
2. May be we need install other Qt plugins also...

### CODE REVIEW

**Comment by Gnurou** [comment]
After finally reviewing this superbly-crafted PR I feel so bad for taking so much time to come back to it. Thank you very much and please accept my apologies for the delay! >_<

**Comment by vovkasm** [comment]
Thank you! :-)

Btw, what is you own way to develop program itself, OS, IDE, etc?
I feel uncomfortable with current project layout, because edit -> run cycle too long on macOS... It would be cool to allow program to start from build tree, but maybe I can simple install same dev environment as your?

**Comment by Gnurou** [comment]
I work with Linux and KDevelop and can run the program from the build tree, but I believe (at least it was true when I was also testing on Mac) that this should also work on Mac.

Basically from a build tree where the program and databases are built, just running ./src/gui/tagainijisho works. Is it behaving differently on Mac, besides the binary being named "Tagaini Jisho" for packaging reasons?

**Comment by vovkasm** [comment]
On Mac there is a need to copy all resources to bundle, so that the app can find them, it takes a lot of time... I'll try KDevelop on Linux, thanks!

**Comment by Gnurou** [comment]
Mmm, it would be nice to be able to find a way to run directly from the tree on Mac. But thanks to your PR I should be able to finally make a release soon!

Note that KDevelop is not mandatory at all on Linux, any IDE/Editor will do just fine (Qt Creator also works quite well for obvious reasons :))

**Pull request merged**
