### PR TITLE
[v2] Fix assert error while parsing XML file.

### PR DESCRIPTION
**Pull request by MyleneJ**
Here is the 2nd pull request about the empty QString when parsing XML file.
Do not hesitate to comment if something is wrong.

PS : I always have an error with Travis Cli. Is it normal ?

### CODE REVIEW

**Comment by Gnurou** [comment]
This looks great!

However you have two patches in your pull branch, the one you submitted first, and the second one that fixes my comments. Could you squash them into a single one (using 'git rebase -i' followed by 'git push --force' is probably the easiest way to do this) to make history easier to read?

The Travis failure is unrelated and not something you should worry about, at least on the Qt5 branch (some Qt5 dependencies are missing for the build, I need to fix that...)

**Comment by MyleneJ** [comment]
Thanks !
Yes, I did not like to "pull request" my two patches but I did not know how to do this. Thank you for the git-rebase info !
Okay for Travis. I have seen that it is related to Qt5 dependencies.

**Comment by Gnurou** [comment]
Merged, thanks!
And for what it's worth, congrats on landing your first patch in this project! ;)

**Comment by MyleneJ** [comment]
Thank you ! 
Yes, it is a small patch but I am happy ! My first contribution  :D

**Pull request merged**
