### PR TITLE
Remove 面（おもて） from JLPT N3 list.

### PR DESCRIPTION
**Pull request by krofna**
According to An Advanced Japanese Reader by Edward E. Daub おもて is a very rare reading of 面, which is usually めん. Also this entry cannot be found  on jlptstudy.net. I assume おもて was supposed to be 表 which is a very common word.

### CODE REVIEW

**Comment by krofna** [comment]
There's also 2571360 (怡怡), which is marked as archaic in jmdict so it actually doesn't even appear on the list by default because tagaini jisho filters archaic and obsolete entries. 2258510 (ガル, gal, a unit of gravitational acceleration) is also a really rare word. Needless to say, these don't appear on online avaliable JLPT word lists either.

**Comment by krofna** [comment]
1198160, 1438200, 1525230, 1690070, 2219600 have "archaic" tag as well so I'm not sure whether or not they are fit for the JLPT list.

**Comment by krofna** [comment]
1186220 - deleted from jmdict
1280050 - obscure

**Comment by Gnurou** [comment]
Sounds reasonable, indeed. These lists were mostly software-created, so a human pass is required to catch these.

I will create more commits for the other entries you suggested.

**Comment by Gnurou** [comment]
Removed most of the other entries you suggested. Thanks and sorry for taking so long to process this!

**Pull request merged**
