### PR TITLE
Now compiles for macOS 10.12

### PR DESCRIPTION
**Pull request by DEGoodmanWilson**
—but with a minimum deployment target of 10.9.

### CODE REVIEW

**Comment by DEGoodmanWilson** [comment]
That said, `cpack` is failing for me. (I'm new to `cpack`, I am sorry)

```
$ cpack -G DragNDrop
CPack: Create package using DragNDrop
CPack: Install projects
CPack: - Run preinstall target for: Tagaini Jisho
CPack: - Install project: Tagaini Jisho
CPack: -   Install component: Databases
CPack: -   Install component: I18n
CPack: -   Install component: Runtime
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open input file: /Users/dgoodman/Documents/Projects/tagainijisho/build/_CPack_Packages/Darwin/DragNDrop/Tagaini Jisho-1.0.3/ALL_IN_ONE/Tagaini Jisho.app/Contents/MacOS/libcrypto.1.0.0.dylib for writing (Permission denied)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't lseek to offset: 0 in file: /Users/dgoodman/Documents/Projects/tagainijisho/build/_CPack_Packages/Darwin/DragNDrop/Tagaini Jisho-1.0.3/ALL_IN_ONE/Tagaini Jisho.app/Contents/MacOS/libcrypto.1.0.0.dylib for writing (Bad file descriptor)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't write new headers in file: /Users/dgoodman/Documents/Projects/tagainijisho/build/_CPack_Packages/Darwin/DragNDrop/Tagaini Jisho-1.0.3/ALL_IN_ONE/Tagaini Jisho.app/Contents/MacOS/libcrypto.1.0.0.dylib (Bad file descriptor)
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't close written on input file: /Users/dgoodman/Documents/Projects/tagainijisho/build/_CPack_Packages/Darwin/DragNDrop/Tagaini Jisho-1.0.3/ALL_IN_ONE/Tagaini Jisho.app/Contents/MacOS/libcrypto.1.0.0.dylib (Bad file descriptor)
CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/BundleUtilities.cmake:834 (message):
  Command failed:

   'install_name_tool' '-id' '@executable_path/../MacOS/libcrypto.1.0.0.dylib' '/Users/dgoodman/Documents/Projects/tagainijisho/build/_CPack_Packages/Darwin/DragNDrop/Tagaini Jisho-1.0.3/ALL_IN_ONE/Tagaini Jisho.app/Contents/MacOS/libcrypto.1.0.0.dylib'
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/BundleUtilities.cmake:902 (fixup_bundle_item)
  /Users/dgoodman/Documents/Projects/tagainijisho/build/pack/cmake_install.cmake:41 (fixup_bundle)
  /Users/dgoodman/Documents/Projects/tagainijisho/build/cmake_install.cmake:35 (include)


CPack Error: Error when generating package: Tagaini Jisho
```

**Comment by Gnurou** [comment]
Mmm, Travis is also not happy with this change it seems... Maybe @Akeru can comment?

**Comment by DEGoodmanWilson** [comment]
Travis doesn't have the OSX 10.12 SDK available, seems to be the issue.

**Comment by Akeru** [comment]
Sorry for the delay.

Travis uses by default XCode 7.3.1 which indeed does not have the OSX 10.12 SDK.

This can be overriden in OSX part of the .travis.yml file by specifying `osx_image: xcode8`.

**Comment by Gnurou** [comment]
Still seeing the same error after adding the line @Akeru suggested:

https://github.com/Gnurou/tagainijisho/commit/a3e9a8cbe29cef9c6eff168c06291bc510ff7e56
https://travis-ci.org/Gnurou/tagainijisho/jobs/168143457

Or am I doing it wrong?

**Comment by Akeru** [comment]
Nope, you're right. Travis did not include the 10.9 SDK in their XCode8. The only SDK is 10.11.

**Comment by DEGoodmanWilson** [comment]
Ugh, the new Xcode doesn't let you download previous SDKs, so I am unable to test it with a previous version on my local machines :sob:

**Comment by Gnurou** [comment]
Seriously, no binary backward compatibility, no way to choose SDK versions... what shit system is that?</rant>

I have tried setting the SDK to 10.11, as @Akeru seemed to suggest, but to no avail:
https://travis-ci.org/Gnurou/tagainijisho/jobs/168779967

Any further suggestion? OSX builds are broken at the moment, so we have no way to provide a binary release...

**Comment by DEGoodmanWilson** [comment]
LGTM! I'll close this issue out.

**Pull request closed without merging**
